- name: Install Atom repo key (Ubuntu 20.04)
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: Install Atom repo (Ubuntu 20.04)
  apt_repository:
    repo: deb https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present

- name: Install Atom (Ubuntu 20.04)
  apt: name=atom state=latest update_cache=yes
