- name: Install Atom PPA (Linux Mint)
  apt_repository:
    repo: ppa:webupd8team/atom
    state: present
    codename: bionic
  when: ansible_distribution == 'Linux Mint' and ansible_distribution_version == '19'

- name: Install Atom PPA (Ubuntu 16.04)
  apt_repository:
    repo: ppa:webupd8team/atom
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Install Atom PPA (Ubuntu 18.04)
  apt_repository:
    repo: ppa:webupd8team/atom
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Install Atom repo key (Ubuntu 20.04)
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install Atom repo (Ubuntu 20.04)
  apt_repository:
    repo: deb https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install Atom
  apt: name=atom state=latest update_cache=yes
