#
# Ansible
#
- name: Install Ansible
  apt: name=ansible state=latest

#
# Vagrant
#
- name: Install Vagrant (Ubuntu 20.04)
  apt: name=vagrant state=latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install Vagrant (Ubuntu 22.04)
  apt: name=vagrant state=latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
