---

- name: 'Install Java JDK (Ubuntu 20.04)'
  apt: name=openjdk-11-jdk
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: 'Install Java JDK (Ubuntu 22.04)'
  apt: name=openjdk-18-jdk
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
