---

- import_tasks: atom-20.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- import_tasks: atom-22.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- import_tasks: automation.yml
  become: yes
  become_user: root

- import_tasks: utilities.yml
  become: yes
  become_user: root

- import_tasks: java.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
