---

- include: atom-20.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- include: atom-22.04.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- include: automation.yml
  become: yes
  become_user: root

- include: utilities.yml
  become: yes
  become_user: root

- include: java.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
