---

- import_tasks: automation.yml
  become: yes
  become_user: root

- import_tasks: utilities.yml
  become: yes
  become_user: root

- import_tasks: java.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
