---

- include: atom.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Linux Mint'

- include: automation.yml
  become: yes
  become_user: root

- include: utilities.yml
  become: yes
  become_user: root

- include: java.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
