---
#
# This should only be done in Ubuntu 16.04 x86_64

- name: Add Selenium group
  user:
    name: "{{ selenium_group }}"
    state: present

- name: Add Selenium user
  user:
    name: "{{ selenium_user }}"
    group: "{{ selenium_group }}"
    shell: /bin/false
    append: yes
    groups: www-data
    home: "{{ selenium_dir }}"

- name: 'Create Selenium directory'
  file:
    path: "{{ selenium_dir }}"
    state: directory
    mode: 0755
    owner: "{{ selenium_user }}"
    group: "{{ selenium_group }}"

- name: Download Selenium server
  get_url:
    url: http://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.0.jar
    dest: "{{ selenium_dir }}/selenium-server-standalone.jar"
    mode: 0755
    owner: "{{ selenium_user }}"
    group: "{{ selenium_group }}"

- name: Download ChromeDriver
  unarchive:
    creates: "{{ selenium_dir }}/chromedriver"
    dest: "{{ selenium_dir }}"
    remote_src: yes
    src: http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip

- name: Install init script
  template:
    src: etc/init.d/selenium.j2
    dest: /etc/init.d/selenium
    mode: 0755

- name: 'Reload SystemD daemon'
  shell: systemctl daemon-reload

- name: 'Start Selenium at Boot'
  shell: update-rc.d selenium defaults 90 90
