---

- name: Install helpful utilities
  apt: name="{{ item }}" state=present
  with_items:
    - bison
    - cloc
    - flex
    - gkrellm
    - kdiff3
    - nmap
    - synaptic
    - xvfb

- name: Install fonts
  apt: name="{{ item }}" state=latest
  with_items:
    - ttf-mscorefonts-installer
    - ttf-xfree86-nonfree
    - xfonts-base
    - xfonts-scalable
    - fonts-dejavu
