---

- name: Install helpful utilities
  apt:
    pkg:
      - bison
      - cloc
      - flex
      - kdiff3
      - nmap
      - xvfb

- name: Install Git related tools
  apt:
    pkg:
      - giggle
      - git
      - git-cola
      - gitg

- name: Install fonts
  apt:
    pkg:
      - ttf-mscorefonts-installer
      - ttf-xfree86-nonfree
      - xfonts-base
      - xfonts-scalable
      - fonts-dejavu

- name: Install Graphviz
  apt: name=graphviz state=present

- name: Install common build utils
  apt:
    pkg:
      - autoconf
      - automake
      - build-essential
      - cmake
      - kcachegrind
      - make

- name: Install MySQL APT sources
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

- name: Install MySQL workbench
  apt:
    name: mysql-workbench-community
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
